#!/usr/bin/env bash

DOTFILES_PATH=${DOTFILES_PATH:-"$(dirname "$(realpath "${BASH_SOURCE[0]}")")"}
export DOTFILES_PATH

. "${DOTFILES_PATH}/bin/lib/init.sh"

dotfiles::sudo_keepalive

# link required files to home directory
. "${DOTFILES_PATH}/bin/sync_dotfiles"

. "${DOTFILES_PATH}/.bash_profile"

# shellcheck disable=SC1090
. "${DOTFILES_PATH}/.init/${PLATFORM-}"

. "${DOTFILES_PATH}/.init/install_homebrew"

# use homebrew bash on macos
if [[ ${PLATFORM-} == "darwin" ]]; then
  hb_bash="${HOMEBREW_PREFIX}/opt/bin/bash" || "$(command -v bash)"

  if ! grep "${hb_bash}" /etc/shells &> /dev/null; then
    echo
    echo "Setting \$SHELL to ${hb_bash}"
    echo

    echo "${hb_bash}" | sudo tee -a /etc/shells &> /dev/null
    sudo chsh -s "${hb_bash}" "${USER}" &> /dev/null

    # verify
    grep "^${USER}" /etc/passwd &> /dev/null || exit 127

    echo "done"
    echo
  fi
fi

# shellcheck source=../bin/update_system
. "${DOTFILES_PATH}/bin/update_system"

echo "bootsrapping asdf"
echo

if command -v asdf &> /dev/null; then
  plugins=$(awk '{print $1}' < "${HOME}/.tool-versions" | tr '\n' ' ')

  for plugin in ${plugins}; do
    asdf plugin add "${plugin}"
  done
  unset plugin

  asdf install
fi

echo "done!"
echo
