#!/usr/bin/env bash

if command -v brew 2&>/dev/null; then
  echo
  echo "homebrew is already installed"
  echo

  return
fi

echo "Installing homebrew and packages..."
echo

if [[ "${PLATFORM-}" == "linux" ]]; then
  echo "installing linux deps"
  echo

  sudo apt-get update && sudo apt-get install -y build-essential curl software-properties-common git ca-certificates
fi

# shellcheck disable=SC2312
NONINTERACTIVE=1 curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash

# shellcheck source=../.bashrc
. "${HOME}/.bash_profile";

if ! command -v brew 2&>/dev/null; then
  echo
  echo "homebrew not available! exiting!"
  echo

  exit 127
fi

brew install gcc
brew doctor

echo
echo "done!"
echo
