k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /Users/j/Downloads/k9s/screendumps
  refreshRate: 2
  maxConnRetry: 5
  noExitOnCtrlC: true
  ui:
    enableMouse: true
    logoless: true
    reactive: true
  shellPod:
    image: busybox:stable
    namespace: default
    limits:
      cpu: 100m
      memory: 256Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -5
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 95
      warn: 80
    memory:
      critical: 95
      warn: 80
