name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Shfmt
        uses: collin-miller/shfmt-action@v1
        with:
          args: -d -s -ln bash -i 2 -ci -sr .

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --rcfile .shellcheckrc
